# Generated by Django 4.1.7 on 2023-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, height_field=50, upload_to='avatars/', width_field=50),
        ),
    ]
